# 플랫폼 감지 및 전역 정의
if(WIN32)
    set(TESSERA_PLATFORM "windows")
    add_compile_definitions(TESSERA_PLATFORM_WINDOWS)
elseif(APPLE)
    set(TESSERA_PLATFORM "macos")
    add_compile_definitions(TESSERA_PLATFORM_MACOS TESSERA_PLATFORM_POSIX)
elseif(UNIX)
    set(TESSERA_PLATFORM "linux")
    add_compile_definitions(TESSERA_PLATFORM_LINUX TESSERA_PLATFORM_POSIX)
else()
    message(FATAL_ERROR "Unsupported platform")
endif()

message(STATUS "Building for platform: ${TESSERA_PLATFORM}")
